MODEL: FeatureMatching
DATASET:
  DATA_SOURCE: 'MapFree'  # To determine the dataloader
  DATA_ROOT: '/Titan/dataset/data_apmp/test_out3/'
  SCENES: [s00000_sample]
  ESTIMATED_DEPTH: None   # To load estimated depth map, provide the suffix to the depth files, e.g. 'dptnyu', 'dptkitti'
  AUGMENTATION_TYPE: None
  HEIGHT: 720             # Images are resized
  WIDTH: 1280
  MIN_OVERLAP_SCORE: 0.2  # [train only] discard data with overlap_score < min_overlap_score
  MAX_OVERLAP_SCORE: 0.7  # [train only] discard data with overlap_score < min_overlap_score
  QUERY_FRAME_COUNT: 1    # 1 (single frame task) or 9 (multi-frame task) only!
PNP:
  RANSAC_ITER: 1000
  REPROJECTION_INLIER_THRESHOLD: 3 # pixel
  CONFIDENCE: 0.9999
EMAT_RANSAC:
  PIX_THRESHOLD: 2.0
  SCALE_THRESHOLD: 0.1
  CONFIDENCE: 0.9999
PROCRUSTES:
  MAX_CORR_DIST: 0.05 # meters
  REFINE: False # refine pose with ICP